name: Codecov

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
