name: codecov

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  codecov:
    name: codecov
    runs-on: ubuntu-latest
    steps:
      - name: Send code coverage report to Codecov.io
        uses: codecov/codecov-action@v2
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
